 version: '3.8'
 services:
  merchandise-service:
   build: 
    context: ../
    dockerfile: Dockerfile
   hostname: merchandise_service
   ports:
    - "8080:80"
   environment:
    DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5426;Database=merchandise-service;Username=postgres;Password=merchandiseServicePassword"
   depends_on:
    - merchandise-service-db

  merchandise-service-db:
   image: postgres:latest
   ports:
    - "5426:5432"
   environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merchandiseServicePassword
      POSTGRES_DB: merchandise-service