 version: '3.8'

 services:
  merchandise-service:
   build: ../src/OzonEdu.MerchandiseService
   hostname: merchandise_service
   ports:
    - "8080:80"
   environment:
    DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5426;Database=merchandise-service;Username=postgres;Password=merchandiseServicePassword"
   depends_on:
    - merchandise-service-bd
    - supply
    - emailing
    - employees
    - stock

  merchandise-service-bd:
   image: postgres:latest
   ports:
    - "5426:5432"
   environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merchandiseServicePassword
      POSTGRES_DB: merchandise-service
   command: "-c log_statement=all"


  supply:
   image: 'ghcr.io/ozon-edu-csharp-2021/supply-service:main'
   hostname: supply
  emailing:
   image: 'ghcr.io/ozon-edu-csharp-2021/emailing-service:main'
   hostname: emailing
  employees:
   image: 'ghcr.io/ozon-edu-csharp-2021/employees-service:main'
   hostname: employees
  stock:
   image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
   hostname: stock